{
 "title": "Cablemodem",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Current Connectivity Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "arris_connectivity_state" }
   ]
  },
  {
   "title": "Rate of Corrected and Uncorrectable Packet Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(arris_downstream_packets_corrected[5m])",
     "legendFormat": "corrected@ch{{channel_id}}"
    },
    {
     "expr": "rate(arris_downstream_packets_uncorrectable[5m])",
     "legendFormat": "uncorrectable@ch{{channel_id}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "content": "\n# Lock Status\nLike an audio modem, cablemodems need to negotiate with their far-side peers to ensure the signal is received.  Lock status indicates that the particular channel in question is \"locked on\", or in sync, with the far end.\n\n\n\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "content": "\n# Signal to Noise Ratio\n[Wolf Paulus - Cable Modem Signal Levels](https://wolfpaulus.com/hardware/cablemodem/):\n> The downstream SNR tells how much noise is on the cable. Again, for the cable modem to work within the specification, the SNR needs to be at least 23.5dB; a desirable ratio is 30 dB or higher.\n\n\n\n"
  },
  {
   "title": "Upstream Channel Locked",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(arris_upstream_locked) by (channel_id)",
     "legendFormat": "channel {{channel_id}}"
    }
   ]
  },
  {
   "title": "Downstream Channel Locked",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(arris_downstream_locked) by (channel_id)",
     "legendFormat": "channel {{channel_id}}"
    }
   ]
  },
  {
   "title": "Downstream SNR",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "expr": "sum(arris_downstream_snr) by (channel_id)",
     "legendFormat": "channel {{channel_id}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "content": "\n# Downstream and Upstream Power\nFrom [netgear support](https://kb.netgear.com/24311/Power-level-guidelines-for-a-NETGEAR-cable-modem-router):\n>Downstream and upstream power levels are important when determining if the cable line that is connected to your cable modem or modem router is receiving sufficient power. Good Downstream power levels are within -7 to +7 dBmV. Good Upstream power levels are within 38-48 dBmV.\n\n\n"
  },
  {
   "title": "Upstream Transmit Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "expr": "sum(arris_upstream_power) by (channel_id)",
     "legendFormat": "channel {{channel_id}}"
    }
   ]
  },
  {
   "title": "Downstream Received Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "expr": "sum(arris_downstream_power) by (channel_id)",
     "legendFormat": "channel {{channel_id}}"
    }
   ]
  }
 ]
}